version: '3.8'

services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=origin
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres
    
  app:
    depends_on:
      - postgresdb
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_HOST=postgresdb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=origin
      - DATABASE_PORT=5432
      - JWT_SECRET=74YLbq4%c!wU
      - JWT_EXPIRATION_TIME=3600
  
volumes:
  db:
